name: Build on PiCloud
on: [push]
jobs:
  check_connection:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Check Connection
        run: echo "Connection successful"
  
  logging:
    needs: check_connection
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Debug Runner Information
        run: |
         ping github.com -c 4
      - name: Alchemy Sync 
        run: |
         cd /home/pi/docker-alchemy/alchemy
         git fetch origin
         git reset --hard origin/main
         echo "✔️ Workflow Completed - Done!" 
